<?php
    require_once('../includes/initialize.php');

    /* This is an app intended to hopefully aid in cleaning up "dirty" data
    generated by confused parents as they signed up for Chromebook pickups.

    Let's start by querying the database for all of our SignUpGenius records.
    */

    $stmt = "SELECT * FROM signups";
    $params = array();
    $results = $database->query($stmt, $params);

    /* $result should be an associative array with the following keys:

        id: Auto-incremented INT
        date_time: Signed up date and time for pickup
        station: Assigned station for pickup
        first_name: First name on sign up - in theory, the goal was parent first
        last_name: Last name on sign up- Goal was parent last name
        email: Email provided for SignupGenius sign up
        comments: Might have some relevant detail
        student_1: First student signed up
        student_2: Second student signed up (opt.)
        student_3: Third student signed up (opt.)
    */

    $signup_names = array();
    foreach($results as $result){
        $curr_name = $result['first_name'] . " " . $result['last_name'];
        array_push($signup_names, $curr_name);
    }


    /* Signup Update Logic

    Once I fix signups, clean up data, combine split signups, match SIS records,
    etc., then we will process all of this info to perform the following:

    - Delete extra, unnecessary record
    - Update/correct erroneously entered data for signups (in same table or
      new corrected_signups table- I lean towards new table)
    - Create database entries in the following tables:
      - students (must go first to generate IDs for pickups table): name (
        pulled by splitting signup_students{$i}), district_id (pulled from
        checked SIS match(es)), dob (pulled from checked SIS match(es))
      - pickups: Parent Name, Date, Time (split these up), Station ID (pull
        from stations table based on station name), students (comma separated,
        no spaces), address, city, state, zip (from checked SIS match(es))

    */

    if(isset($_POST['submit_signup'])){
      $num_signups = $_POST['signup_matches']; // Set how many matching signups were found.
      $num_siss = $_POST['sis_matches']; // Set how many matching sis records were found.

      $sis_keeps = array();
      if(isset($_POST['sis_select'])){
        $sis_keeps = $_POST['sis_select'];
      } // Should return an array with indexes of any SIS records to use
      $student_ids = array();

      if(!empty($sis_keeps)){
        foreach($sis_keeps as $index){
          $this_id = $_POST["student_id_{$index}"];
          array_push($student_ids, $this_id);
        }

        $sis_records = array();
        // Set up select statement; We will execute each time, swapping out the ID and pushing result into $sis_records
        $stmt = "SELECT * FROM sis ";
        $stmt .= "WHERE district_id=:id ";
        $stmt .= "LIMIT 1";
        foreach($student_ids as $id){
          $params = array(":id"=>$id);
          $sis_result = $database->query($stmt, $params);
          array_push($sis_records, $sis_result[0]);
        }


      } // End sis_keeps

      // Now we have these sis records to build the pickups and students
      // Loop through matched signups, check if information updated
      for($x=0; $x<$num_signups; $x++){
        if(isset($_POST["signup_upload{$x}"])){
          // If upload set to yes, create/update records in corrected_signups, pickups, and students
          if($_POST["signup_upload{$x}"] == "Yes"){
            // Start with corrected_signups- first check if creating or updating

            $parent_name = explode(" ", $_POST["parent_name{$x}"]);
            $stmt = "SELECT * FROM corrected_signups ";
            $stmt .= "WHERE first_name=:first_name ";
            $stmt .= "AND last_name=:last_name";
            $params = array(":first_name"=>$parent_name[0], ":last_name"=>$parent_name[1]);

            $corrected_check_result = $database->query($stmt, $params);
            if(!empty($corrected_check_result)){
              // Something already in corrected_signups, let's update
              echo "Record already exists. Update manually";
            //   $curr_dt = $_POST["signup_dt{$x}"];
            //   $curr_station = $_POST["signup_station{$x}"];
            //   $curr_pname = explode(" ", $_POST["parent_name{$x}"]);
            //   $curr_fn = $curr_pname[0];
            //   $curr_ln = $curr_pname[1];
            //   $curr_email = $_POST["signup_email{$x}"];
            //   $curr_comments = $_POST["comments{$x}"];
            //   $curr_students = explode(", ", $_POST["signup_students{$x}"]);
            //   $curr_student1 = $curr_students[0];
            //   (count($curr_students) >= 2) ? $curr_student2 = $curr_students[1] : $curr_student2 = null;
            //   (count($curr_students) > 2) ? $curr_student3 = $curr_students[2] : $curr_student3 = null;
              //
            //   $stmt = "UPDATE corrected_signups ";
            //   $stmt .= "SET date_time=:date_time, ";
            //   $stmt .= "station=:station, ";
            //   $stmt .= "first_name=:first_name, ";
            //   $stmt .= "last_name=:last_name, ";
            //   $stmt .= "email=:email, ";
            //   $stmt .= "comments=:comments, ";
            //   $stmt .= "student_1=:student_1, ";
            //   $stmt .= "student_2=:student_2, ";
            //   $stmt .= "student_3=:student_3";
              //
            //   $params = array(":date_time"=>$curr_dt, ":station"=>$curr_station, ":first_name"=>$curr_fn, ":last_name"=>$curr_ln, ":email"=>$curr_email, ":comments"=>$curr_comments, ":student_1"=>$curr_student1, ":student_2"=>$curr_student2, ":student_3"=>$curr_student3);
              //
            //   $result = $database->cud_query($stmt, $params);
              //
            //   if($result>0){
            //     echo "Successful Update!";
            //   } else {
            //     echo "Something went wrong";
            //   }
              //
            //   // Also update students and pickups
            //   if(!empty($sis_keeps)){
            //     $student_ids = array();
            //     foreach ($curr_students as $student) {
            //       foreach($sis_records as $record){
              //
            //         $record_name = $record['student_fn'] . " " . $record['student_ln']; // Combine student first and last name fields from sis
              //
            //         if(strtoupper($student) == $record_name){ // If we have a match, update student with district_id and dob from sis
              //
            //           $stmt = "UPDATE students ";
            //           $stmt .= "SET name=:name, ";
            //           $stmt .= "district_id=:district_id, ";
            //           $stmt .= "dob=:dob";
              //
            //           $params = array(":name"=>$student, ":district_id"=>$record['district_id'], ":dob"=>$record['dob']);
              //
            //           $student_result = $database->cud_query($stmt, $params);
              //
            //           if($student_result>0){
            //             echo "Successful student update!";
            //           } else {
            //             echo "Something went wrong";
            //           }
            //         } // End student update
              //
              //
            //       }
              //
            //     }
              //
            //     // Have to loop through creating each student, then we can create pickup
            //     // since we are still inside if(!empty($sis_keeps)), we know we have at least $sis_records[0] to get address
            //     // Still in for $x loop, so can use $x index
            //     $parent_name = $_POST["parent_name{$x}"];
            //     $date_time = explode(" ", $_POST["signup_dt{$x}"]);
            //     $date = $date_time[0];
            //     $time = $date_time[1];
            //     $pickup_station_id = $_POST["signup_station{$x}"];
            //     if(count($student_ids)>1){
            //       $students = implode(",",$student_ids);
            //     } else {
            //       $students = $student_ids[0];
            //     }
            //     $address = $sis_records[0]['address'];
            //     $city = $sis_records[0]['city'];
            //     $state = $sis_records[0]['state'];
            //     $zip = $sis_records[0]['zip'];
              //
            //     $stmt = "INSERT INTO pickups ";
            //     $stmt .= "(parent_name, date, time, station_id, students, address, city, state, zip) ";
            //     $stmt .= "VALUES (:parent_name, :date, :time, :station_id, :students, :address, :city, :state, :zip)";
              //
            //     $params = array(":parent_name"=>$parent_name, ":date"=>$date, ":time"=>$time, ":station_id"=>$pickup_station_id, ":students"=>$students, ":address"=>$address, ":city"=>$city, ":state"=>$state, ":zip"=>$zip);
              //
            //     $pickup_result = $database->cud_query($stmt, $params);
              //
            //     if($pickup_result>0){
            //       echo "Successful pickup Insert!";
            //     } else {
            //       echo "Something went wrong";
            //     }
              //
            //     // Follow up creation with SELECT to get id, add to $student_ids array
            //     $stmt = "SELECT * FROM students ";
            //     $stmt .= "WHERE district_id=:district_id";
            //     $params = array(":district_id"=>$record['district_id']);
              //
            //     $get_student_result = $database->query($stmt, $params);
            //     if(!empty($get_student_result)){
            //       array_push($student_ids, $get_student_result[0]['id']);
            //     }

              //} // End students inserts

              // Update students and pickups

            } else{
              // Nothing in corrected_signups, new insert
              $curr_dt = $_POST["signup_dt{$x}"];
              $curr_station = $_POST["signup_station{$x}"];
              $curr_pname = explode(" ", $_POST["parent_name{$x}"]);
              $curr_fn = $curr_pname[0];
              $curr_ln = $curr_pname[1];
              $curr_email = $_POST["signup_email{$x}"];
              $curr_comments = $_POST["comments{$x}"];
              $curr_students = explode(", ", $_POST["signup_students{$x}"]);
              $curr_student1 = $curr_students[0];
              (count($curr_students) >= 2) ? $curr_student2 = $curr_students[1] : $curr_student2 = null;
              (count($curr_students) > 2) ? $curr_student3 = $curr_students[2] : $curr_student3 = null;


              $stmt = "INSERT INTO corrected_signups ";
              $stmt .= "(date_time, station, first_name, last_name, email, comments, student_1, student_2, student_3) ";
              $stmt .= "VALUES (:date_time, :station, :first_name, :last_name, :email, :comments, :student_1, :student_2, :student_3)";
              $params = array(":date_time"=>$curr_dt, ":station"=>$curr_station, ":first_name"=>$curr_fn, ":last_name"=>$curr_ln, ":email"=>$curr_email, ":comments"=>$curr_comments, ":student_1"=>$curr_student1, ":student_2"=>$curr_student2, ":student_3"=>$curr_student3);

              $result = $database->cud_query($stmt, $params);

              if($result>0){
                echo "Successful Insert!";
              } else {
                echo "Something went wrong";
              }

              // Also insert into students and pickups
              if(!empty($sis_keeps)){
                $student_ids = array();
                foreach ($curr_students as $student) {
                  foreach($sis_records as $record){
                    $record_name = $record['student_fn'] . " " . $record['student_ln']; // Combine student first and last name fields from sis

                    if(strtoupper($student) == $record_name){ // If we have a match, create new student with district_id and dob from sis

                      $stmt = "INSERT INTO students ";
                      $stmt .= "(name, district_id, dob) ";
                      $stmt .= "VALUES (:name, :district_id, :dob)";

                      $params = array(":name"=>$student, ":district_id"=>$record['district_id'], ":dob"=>$record['dob']);

                      $student_result = $database->cud_query($stmt, $params);

                      if($student_result>0){
                        echo "Successful student Insert!";
                      } else {
                        echo "Something went wrong";
                      }

                      // Follow up creation with SELECT to get id, add to $student_ids array
                      $stmt = "SELECT * FROM students ";
                      $stmt .= "WHERE district_id=:district_id";
                      $params = array(":district_id"=>$record['district_id']);

                      $get_student_result = $database->query($stmt, $params);
                      if(!empty($get_student_result)){
                        array_push($student_ids, $get_student_result[0]['id']);
                      }

                    } // End student create if matched

                  } // End individual sis record

                } // End curr_student

                // Have to loop through creating each student, then we can create pickup
                // since we are still inside if(!empty($sis_keeps)), we know we have at least $sis_records[0] to get address
                // Still in for $x loop, so can use $x index
                $parent_name = $_POST["parent_name{$x}"];
                $date_time = explode(" ", $_POST["signup_dt{$x}"]);
                $date = $date_time[0];
                $time = $date_time[1];
                $pickup_station_id = $_POST["signup_station{$x}"];
                if(count($student_ids)>1){
                  $students = implode(",",$student_ids);
                } else {
                  $students = $student_ids[0];
                }
                $address = $sis_records[0]['address'];
                $city = $sis_records[0]['city'];
                $state = $sis_records[0]['state'];
                $zip = $sis_records[0]['zip'];

                $stmt = "INSERT INTO pickups ";
                $stmt .= "(parent_name, date, time, station_id, students, address, city, state, zip) ";
                $stmt .= "VALUES (:parent_name, :date, :time, :station_id, :students, :address, :city, :state, :zip)";

                $params = array(":parent_name"=>$parent_name, ":date"=>$date, ":time"=>$time, ":station_id"=>$pickup_station_id, ":students"=>$students, ":address"=>$address, ":city"=>$city, ":state"=>$state, ":zip"=>$zip);

                $pickup_result = $database->cud_query($stmt, $params);

                if($pickup_result>0){
                  echo "Successful pickup Insert!";
                } else {
                  echo "Something went wrong";
                }

              } // End students inserts

            }

          }

        }
      } // End Signup Upload to corrected_signups



      // if(!empty($student_ids)){
      //   foreach ($student_ids as $curr_id) {
      //     echo "<h1>{$curr_id}</h1>";
      //   }
      // }

    }



?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>SignUpGenius Data Cleanup</title>
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.js"></script>
        <script src="js/bootstrap.min.js" charset="utf-8"></script>
    </head>
    <body class="bg-primary text-white">

      <section id="main" class="container-fluid top-buffer mx-auto">
        <form class="" action="data_cleanup.php" method="post">
          <div class="row">

              <div id="signup_info" class="col-6">

                      <div class="row row-buffer align-items-end">
                          <fieldset class="offset-1 col-11"> <!-- Name Picker -->
                              <label for="signup_picker" class="form-control-label">Pick a Sign-up Name:</label>
                              <select id="signup_picker" class="signup-picker" name="signup_picker">
                                  <option selected disabled>--</option>
                                  <?php
                                      foreach($signup_names as $name){
                                          echo "<option value='{$name}'>{$name}</option>";
                                      }
                                  ?>
                              </select>
                              <script type="text/javascript">
                              <?php
                                  if(isset($_POST['submit_name']) or isset($_POST['submit_sis'])){
                              ?>
                                  $(document).ready(function() {
                                      $("#signup_picker").val("<?php echo $_POST['signup_picker']; ?>");
                                  });
                              <?php
                                  }
                                  if(isset($_POST['submit_signup'])){
                              ?>
                                  $(document).ready(function() {
                                      $("#signup_picker").val("<?php echo $_POST['signup_picker']; ?>");
                                      <?php
                                        // Update information for signups if I made any changes
                                        for($x=0; $x<$num_signups; $x++){
                                          $parent_name_val = $_POST["parent_name{$x}"];
                                          echo "$('[name=\"parent_name{$x}\"]').val('{$parent_name_val}');";

                                          $email_val = $_POST["signup_email{$x}"];
                                          echo "$('[name=\"signup_email{$x}\"]').val('{$email_val}');";

                                          $comment_val = $_POST["comments{$x}"];
                                          echo "$('[name=\"comments{$x}\"]').val('{$comment_val}');";

                                          $students_val = $_POST["signup_students{$x}"];
                                          echo "$('[name=\"signup_students{$x}\"]').val('{$students_val}');";
                                        }
                                      ?>
                                  });
                              <?php
                                  }
                              ?>
                              </script>
                          </fieldset> <!-- End Name Picker Dropdown -->

                          <div class="w-100"></div><!--Bootstrap tool for new line with grid layout -->

                          <input type="submit" name="submit_name" value="Submit Name" class="btn btn-danger offset-1 col-2">

                      </div>

                          <?php
                              if(isset($_POST['submit_name']) or isset($_POST['submit_signup']) or isset($_POST['submit_sis'])){
                                  $signup_name = $_POST['signup_picker'];
                                  $signup_split = explode(" ", $signup_name, 2);

                                  // Pull record from signups first to get student names and signup email
                                  $stmt = "SELECT * FROM signups ";
                                  $stmt .= "WHERE first_name=:first_name ";
                                  $stmt .= "AND last_name=:last_name";
                                  $params = array(":first_name"=>$signup_split[0], ":last_name"=>$signup_split[1]);

                                  // Execute query
                                  $signup_results = $database->query($stmt, $params);

                                  if(!empty($signup_results)){ // If we found results (we should), display information below dropdown
                                      $i=0;
                                      $num_results = count($signup_results);
                                      echo "<input type='text' name='signup_matches' value='{$num_results}' hidden>";
                                      foreach ($signup_results as $found) {
                                          $signup_dt = $found['date_time'];
                                          $signup_station = $found['station'];
                                          $signup_first = $found['first_name'];
                                          $signup_last = $found['last_name'];
                                          $signup_email = $found['email'];
                                          $signup_comments = $found['comments'];
                                          $signup_student1 = $found['student_1'];
                                          $signup_student2 = $found['student_2'];
                                          $signup_student3 = $found['student_3'];
                                          $signup_id = $found['id'];

                                          echo "<div class='row top-buffer mt-4'>";
                                          echo "<div class='offset-1 col-10 station'>";
                                          echo "<input type='text' name='signup_id{$i}' value='{$signup_id}' hidden>";
                                          echo "<input type='text' name='parent_name{$i}' value='{$signup_first} {$signup_last}' class='form-control'><div class='w-100'></div>";
                                          echo "<span class='col-2'>{$signup_station} </span>";
                                          echo "<input type='text' name='signup_station{$i}' value='{$signup_station}' hidden>";
                                          echo "<input type='text' name='signup_dt{$i}' value='{$signup_dt}' hidden>";
                                          echo "<span class=''>{$signup_dt}</span><div class='w-100'></div>";
                                          echo "<label for='signup_email{$i}' class='form-control-label'>Email:</label><div class='w-100'></div>";
                                          echo "<input type='text' name='signup_email{$i}' value='{$signup_email}' class='form-control'><div class='w-100'></div>";
                                          echo "<label for='comments{$i}' class='form-control-label'>Comments:</label><div class='w-100'></div>";
                                          echo "<input type='textarea' name='comments{$i}' value='{$signup_comments}' class='form-control'><div class='w-100'></div>";
                                          echo "<label for='signup_students{$i}' class='form-control-label'>Student(s):</label><div class='w-100'></div>";
                                          echo "<input type='text' name='signup_students{$i}' value='{$signup_student1}, {$signup_student2}, {$signup_student3}' class='form-control'><div class='w-100'></div>";
                                          echo "<label for='signup_delete{$i}' class='form-control-label'>Delete this record?:</label><div class='w-100'></div>";
                                          echo "<input type='radio' name='signup_delete{$i}' value='Yes' class='form-control'>Yes";
                                          echo "<input type='radio' name='signup_delete{$i}' value='No' class='form-control' checked>No<div class='w-100'></div>";
                                          echo "<label for='signup_upload{$i}' class='form-control-label'>Upload this record?:</label><div class='w-100'></div>";
                                          echo "<input type='radio' name='signup_upload{$i}' value='Yes' class='form-control'>Yes";
                                          echo "<input type='radio' name='signup_upload{$i}' value='No' class='form-control' checked>No<div class='w-100'></div>";
                                          echo "</div>";
                                          echo "</div>";

                                          $i++;
                                      }

                                      echo "<input type='submit' name='submit_signup' value='Submit Signup' class='btn btn-danger offset-9 col-2 mb-4 mt-2'>";
                                  }

                              }
                          ?>

              </div> <!-- End signup_info -->

            <div id="sis_info" class="col-6">
                <div class="row row-buffer">
                    <div class="offset-1 col-11">
                        <h4><u>SIS Potential Matches</u></h4>
                        <input type='text' name='sis_search' placeholder='SIS Search' class='form-control col-8'>
                        <input type="submit" name="submit_sis" value="Search" class="btn btn-danger offset-6 col-2">
                        <?php

                          if(isset($_POST['submit_sis'])){
                              $sis_name = $_POST['sis_search'];
                              // Search sis table for name match on student last name, parent last name, email
                              $stmt = "SELECT * FROM sis ";
                              $stmt .= "WHERE student_ln=:student_ln";

                              $params = array(":student_ln"=>$sis_name);

                              // Execute query
                              $sis_results = $database->query($stmt, $params);
                              $j=1;
                              if(!empty($sis_results)){

                                  $num_sis_results = count($sis_results);
                                  echo "<input type='text' name='sis_matches' value='{$num_sis_results}' hidden>";

                                  foreach($sis_results as $found){
                                      echo "<fieldset id='sis-{$j}'";
                                      $student_name = $found['student_fn'] ." ". $found['student_ln'];
                                      echo "<span class='top-buffer'>Student: {$student_name}</span><div class='w-100'></div>";
                                      $student_email = $found['student_email'];
                                      echo "<span class='top-buffer'>Student Email: {$student_email}</span><div class='w-100'></div>";
                                      $parent_name = $found['parent_name'];
                                      echo "<span class='mb-4'>Parent: {$parent_name}</span><div class='w-100'></div>";

                                      $parent_email = $found['parent_email'];
                                      echo "<span class='top-buffer'>Parent Email: {$parent_email}</span><div class='w-100'></div>";

                                      $stud_id = $found['district_id'];
                                      echo "<input type='text' name='student_id_{$j}' value='{$stud_id}' hidden>"; // Hidden field with student district number to look back up on submit
                                      echo "<input type='checkbox' name='sis_select[]' value='{$j}'> &nbsp; Use this record";
                                      // If they choose this record, we will use $sis_results[value] to pull sis data and insert into pickup info
                                      echo "<hr style='border-color: white;' class='col-4 ml-0'>";
                                      echo "</fieldset>";

                                      $j++;
                                  }
                              } else {
                                  echo "<h6>No results found</h6>";
                              } // End SIS Search

                              $sis_name = $_POST['signup_picker'];
                              $sis_split = explode(" ", $sis_name);
                              $sis_email = null;
                              // Search sis table for name match on student last name, parent last name, email
                              $stmt = "SELECT * FROM sis ";
                              $stmt .= "WHERE student_ln=:student_ln ";
                              $stmt .= "OR student_email=:student_email ";
                              $stmt .= "OR parent_email=:parent_email ";
                              $stmt .= "OR parent_name=:parent_name";

                              if(!empty($signup_results)){
                                  $sis_email = $signup_results[0]['email'];
                              }

                              $params = array(":student_ln"=>$sis_split[1], ":student_email"=>$sis_email, ":parent_email"=>$sis_email, ":parent_name"=>$sis_name);

                              // Execute query
                              $sis_results = $database->query($stmt, $params);

                              if(!empty($sis_results)){

                                  $num_sis_results = count($sis_results);
                                  echo "<input type='text' name='sis_matches' value='{$num_sis_results}' hidden>";

                                  foreach($sis_results as $found){
                                      echo "<fieldset id='sis-{$j}'";
                                      $student_name = $found['student_fn'] ." ". $found['student_ln'];
                                      echo "<span class='top-buffer'>Student: {$student_name}</span><div class='w-100'></div>";
                                      $student_email = $found['student_email'];
                                      echo "<span class='top-buffer'>Student Email: {$student_email}</span><div class='w-100'></div>";
                                      $parent_name = $found['parent_name'];
                                      echo "<span class='mb-4'>Parent: {$parent_name}</span><div class='w-100'></div>";

                                      $parent_email = $found['parent_email'];
                                      echo "<span class='top-buffer'>Parent Email: {$parent_email}</span><div class='w-100'></div>";

                                      $stud_id = $found['district_id'];
                                      echo "<input type='text' name='student_id_{$j}' value='{$stud_id}' hidden>"; // Hidden field with student district number to look back up on submit
                                      echo "<input type='checkbox' name='sis_select[]' value='{$j}'> &nbsp; Use this record";
                                      // If they choose this record, we will use $sis_results[value] to pull sis data and insert into pickup info
                                      echo "<hr style='border-color: white;' class='col-4 ml-0'>";
                                      echo "</fieldset>";

                                      $j++;
                                  }
                              } else {
                                  echo "<h6>No results found</h6>";
                              }

                            }
                            if(isset($_POST['submit_name']) or isset($_POST['submit_signup'])){
                                $sis_name = $_POST['signup_picker'];
                                $sis_split = explode(" ", $sis_name);
                                $sis_email = null;
                                // Search sis table for name match on student last name, parent last name, email
                                $stmt = "SELECT * FROM sis ";
                                $stmt .= "WHERE student_ln=:student_ln ";
                                $stmt .= "OR student_email=:student_email ";
                                $stmt .= "OR parent_email=:parent_email ";
                                $stmt .= "OR parent_name=:parent_name";

                                if(!empty($signup_results)){
                                    $sis_email = $signup_results[0]['email'];
                                }

                                $params = array(":student_ln"=>$sis_split[1], ":student_email"=>$sis_email, ":parent_email"=>$sis_email, ":parent_name"=>$sis_name);

                                // Execute query
                                $sis_results = $database->query($stmt, $params);

                                if(!empty($sis_results)){
                                    $j=1;

                                    $num_sis_results = count($sis_results);
                                    echo "<input type='text' name='sis_matches' value='{$num_sis_results}' hidden>";

                                    foreach($sis_results as $found){
                                        echo "<fieldset id='sis-{$j}'";
                                        $student_name = $found['student_fn'] ." ". $found['student_ln'];
                                        echo "<span class='top-buffer'>Student: {$student_name}</span><div class='w-100'></div>";
                                        $student_email = $found['student_email'];
                                        echo "<span class='top-buffer'>Student Email: {$student_email}</span><div class='w-100'></div>";
                                        $parent_name = $found['parent_name'];
                                        echo "<span class='mb-4'>Parent: {$parent_name}</span><div class='w-100'></div>";

                                        $parent_email = $found['parent_email'];
                                        echo "<span class='top-buffer'>Parent Email: {$parent_email}</span><div class='w-100'></div>";

                                        $stud_id = $found['district_id'];
                                        echo "<input type='text' name='student_id_{$j}' value='{$stud_id}' hidden>"; // Hidden field with student district number to look back up on submit
                                        echo "<input type='checkbox' name='sis_select[]' value='{$j}'> &nbsp; Use this record";
                                        // If they choose this record, we will use $sis_results[value] to pull sis data and insert into pickup info
                                        echo "<hr style='border-color: white;' class='col-4 ml-0'>";
                                        echo "</fieldset>";

                                        $j++;
                                    }
                                } else {
                                    echo "<h6>No results found</h6>";
                                }

                            }
                        ?>
                    </div>
                </div> <!-- End sis_info inner row -->
            </div> <!-- End sis_info -->



        </div><!-- End container row -->

        </form>

        </section> <!-- End main section -->
        <footer class="ml-2 footer fixed-bottom">Made by Evan McCullough</footer>
    </body>
</html>

<?php if(isset($database)) { $database->close_connection(); } ?>
